"use strict";
let nida = 1;
let naima = 2;
let sara = 3;
let sana = 4;
let anum = 5;
console.log("Is nida==0 ? I predict false");
console.log(nida == 0);
console.log("Is nida==1 ? I predict True.");
console.log(nida == 1);
console.log("Is naima==1 ? I predict false.");
console.log(naima == 1);
console.log("Is naima==2 ? I predict true.");
console.log(naima == 2);
console.log("Is sara==2 ? I predict false.");
console.log(sara == 2);
console.log("Is sara==3 ? I predict True.");
console.log(sara == 3);
console.log("Is sana==3 ? I predict false.");
console.log(sana == 3);
console.log("Is sana==3 ? I predict true.");
console.log(sana == 4);
console.log("Is anum==4 ? I predict false .");
console.log(anum == 4);
console.log("Is anum==5 ? I predict true.");
console.log(anum == 5);
